### ISSUE TITLE
Install error if compilerOptions are not existing in tsconfig

### ISSUE THREAD

**Issue by schulzi66** [gahjs/core#75]
If no compilerOptions are set in the tsconfig this error occurs during _gah install_

Event 'BEFORE_CLEAN_GAH_FOLDER' fired
Install failed during step: CLEAN_TS_CONFIG
TypeErrorCannot read property 'paths' of undefinedTypeError: Cannot read property 'paths' of undefined
    at TsConfigFile.clean (C:\Users\svc_tfs_build04\AppData\Local\Yarn\Data\global\node_modules\@gah\cli\lib\install-helper\ts-config-file.js:21:45)
    at InstallUnit.action (C:\Users\svc_tfs_build04\AppData\Local\Yarn\Data\global\node_modules\@gah\cli\lib\install-helper\gah-module-def.js:96:38)
    at C:\Users\svc_tfs_build04\AppData\Local\Yarn\Data\global\node_modules\@gah\cli\lib\install-helper\gah-module-base.js:156:61
    at GahModuleDef.listenForFinishedUnit (C:\Users\svc_tfs_build04\AppData\Local\Yarn\Data\global\node_modules\@gah\cli\lib\install-helper\gah-module-base.js:132:27)
    at GahModuleDef.checkUnitDependencies (C:\Users\svc_tfs_build04\AppData\Local\Yarn\Data\global\node_modules\@gah\cli\lib\install-helper\gah-module-base.js:156:22)

This is the last execution error: (This did not necessarily create this error)

**Comment by LoaderB0T** [comment]
Hi Marius,

thanks for the issue. I can confirm this is a bug.
